apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    eks.amazonaws.com/role-arn: {{ .Value.globa.ROLE_ARN}}
  labels:
    app.kubernetes.io/managed-by: helm
  name: {{ .Values.global.APP_NAME}}