apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.global.APP_NAME}}
  labels:
    app: {{ .Values.global.APP_NAME}}
    service: {{ .Values.global.APP_NAME}}
spec:
  ports:
  - port: {{ .Values.global.APP_PORT}}
    name: http
  selector:
    app: {{ .Values.global.APP_NAME}}