apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: {{ .Values.global.APP_NAME}}
spec:
  hosts:
  - "*"
  gateways:
  - {{ .Values.global.APP_NAME}}-gateway
  http:
  - match:
    - uri:
        exact: /
    route:
    - destination:
        host: {{ .Values.global.APP_NAME}}
        port:
          number: {{ .Values.global.APP_PORT}}